"use client";

import { FormEvent, useEffect, useRef, useState } from "react";
import { AnimatePresence, motion } from "motion/react";
import { Bot, CalendarDays, CheckCircle2, Loader2, MessageCircle, Send, Sparkles, UserRound, X } from "lucide-react";

type ChatItem={sender:"ASSISTANT"|"VISITOR";content:string};
type Mode="chat"|"quote"|"booking";
const starter:ChatItem={sender:"ASSISTANT",content:"Hello! I’m Rennovex Assistant. I can help you choose a service, request a quote, book a consultation, or connect with our team. What are you planning to build?"};

export function RennovexAssistant(){
 const [open,setOpen]=useState(false); const [mode,setMode]=useState<Mode>("chat"); const [messages,setMessages]=useState<ChatItem[]>([starter]); const [sessionId,setSessionId]=useState<string>(); const [loading,setLoading]=useState(false); const [status,setStatus]=useState(""); const bottomRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{bottomRef.current?.scrollIntoView({behavior:"smooth"})},[messages,mode]);
 async function send(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const data=new FormData(form);const message=String(data.get("message")||"").trim();if(!message||loading)return;setMessages(v=>[...v,{sender:"VISITOR",content:message}]);form.reset();setLoading(true);try{const response=await fetch("/api/assistant",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({sessionId,message})});const result=await response.json();if(!response.ok)throw new Error(result.error);setSessionId(result.sessionId);setMessages(v=>[...v,{sender:"ASSISTANT",content:result.reply}]);if(result.action)setMode(result.action);}catch(error){setMessages(v=>[...v,{sender:"ASSISTANT",content:error instanceof Error?error.message:"Please try again."}])}finally{setLoading(false)}}
 async function submitLead(e:FormEvent<HTMLFormElement>,kind:"quote"|"booking"){e.preventDefault();setLoading(true);setStatus("");const form=e.currentTarget;const payload=Object.fromEntries(new FormData(form));try{const response=await fetch(kind==="quote"?"/api/quotes":"/api/bookings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok)throw new Error(result.error);setStatus(`Submitted successfully. Reference: ${result.reference}`);form.reset();setMessages(v=>[...v,{sender:"ASSISTANT",content:`Your ${kind==="quote"?"quote request":"consultation request"} has been received. Reference: ${result.reference}. Our team will follow up.`}]);setTimeout(()=>setMode("chat"),1800);}catch(error){setStatus(error instanceof Error?error.message:"Please try again.")}finally{setLoading(false)}}
 return <>
  <button type="button" onClick={()=>setOpen(true)} className="fixed bottom-[max(1.25rem,env(safe-area-inset-bottom))] right-4 z-40 inline-flex min-h-12 items-center gap-2 rounded-full bg-blue-700 px-4 py-3 text-sm font-bold text-white shadow-xl shadow-blue-900/25 transition hover:-translate-y-0.5 hover:bg-blue-800 sm:bottom-[max(1.5rem,env(safe-area-inset-bottom))] sm:right-6" aria-label="Open Rennovex Assistant"><MessageCircle size={20}/><span className="hidden sm:inline">Rennovex Assistant</span></button>
  <AnimatePresence>{open&&<><button type="button" aria-label="Close assistant" className="fixed inset-0 z-[70] bg-slate-950/35" onClick={()=>setOpen(false)}/><motion.section className="fixed inset-x-3 bottom-3 z-[80] flex max-h-[88vh] flex-col overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-2xl sm:inset-x-auto sm:bottom-6 sm:right-6 sm:w-[410px]" initial={{opacity:0,y:28,scale:.97}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:20,scale:.98}}>
   <header className="flex items-center justify-between bg-gradient-to-r from-blue-700 to-indigo-700 px-4 py-4 text-white"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-white/15"><Bot size={24}/></div><div><p className="font-bold">Rennovex Assistant</p><p className="text-xs text-blue-100">Digital project advisor</p></div></div><button onClick={()=>setOpen(false)} className="grid h-10 w-10 place-items-center rounded-xl hover:bg-white/10" aria-label="Close"><X size={20}/></button></header>
   <div className="flex gap-2 overflow-x-auto border-b border-slate-100 px-4 py-3 text-xs font-bold"><button onClick={()=>setMode("chat")} className={`rounded-full px-3 py-2 ${mode==="chat"?"bg-blue-700 text-white":"bg-slate-100 text-slate-600"}`}>Chat</button><button onClick={()=>setMode("quote")} className={`rounded-full px-3 py-2 ${mode==="quote"?"bg-blue-700 text-white":"bg-slate-100 text-slate-600"}`}>Request a quote</button><button onClick={()=>setMode("booking")} className={`rounded-full px-3 py-2 ${mode==="booking"?"bg-blue-700 text-white":"bg-slate-100 text-slate-600"}`}>Book consultation</button></div>
   {mode==="chat"?<><div className="min-h-0 flex-1 space-y-3 overflow-y-auto bg-slate-50 px-4 py-4">{messages.map((item,index)=><div key={index} className={`flex gap-2 ${item.sender==="VISITOR"?"justify-end":"justify-start"}`}>{item.sender==="ASSISTANT"&&<div className="grid h-8 w-8 shrink-0 place-items-center rounded-xl bg-blue-100 text-blue-700"><Sparkles size={15}/></div>}<div className={`max-w-[82%] rounded-2xl px-3.5 py-3 text-sm leading-6 ${item.sender==="VISITOR"?"rounded-br-md bg-blue-700 text-white":"rounded-bl-md border border-slate-200 bg-white text-slate-700"}`}>{item.content}</div></div>)}{loading&&<div className="flex items-center gap-2 text-sm text-slate-500"><Loader2 className="animate-spin" size={16}/> Rennovex Assistant is typing…</div>}<div ref={bottomRef}/></div><form onSubmit={send} className="flex gap-2 border-t border-slate-200 bg-white p-3"><input name="message" className="field !py-2.5" placeholder="Ask about a project or service…" maxLength={1200}/><button disabled={loading} className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-blue-700 text-white hover:bg-blue-800 disabled:opacity-50" aria-label="Send"><Send size={18}/></button></form></>:mode==="quote"?<LeadForm kind="quote" loading={loading} status={status} onSubmit={e=>submitLead(e,"quote")}/>:<LeadForm kind="booking" loading={loading} status={status} onSubmit={e=>submitLead(e,"booking")}/>}</motion.section></>}</AnimatePresence>
 </>
}

function LeadForm({kind,loading,status,onSubmit}:{kind:"quote"|"booking";loading:boolean;status:string;onSubmit:(e:FormEvent<HTMLFormElement>)=>void}){return <form onSubmit={onSubmit} className="min-h-0 flex-1 space-y-3 overflow-y-auto p-4"><div className="rounded-2xl bg-blue-50 p-4"><div className="flex items-center gap-2 font-bold text-blue-900">{kind==="quote"?<Sparkles size={18}/>:<CalendarDays size={18}/>} {kind==="quote"?"Project quote request":"Consultation booking"}</div><p className="mt-1 text-sm leading-6 text-blue-700">Complete the details below and the Rennovex team will follow up.</p></div><div className="grid grid-cols-2 gap-3"><input className="field col-span-2 sm:col-span-1" name="name" placeholder="Full name" required/><input className="field col-span-2 sm:col-span-1" name="company" placeholder="Company"/><input className="field col-span-2" name="email" type="email" placeholder="Email address" required/><input className="field col-span-2" name="phone" placeholder="Phone number"/></div><select className="field" name="service" required><option value="">Select a service</option><option>Business Website</option><option>E-commerce Website</option><option>Custom Software</option><option>UI/UX & Branding</option><option>IT Consulting</option></select>{kind==="quote"?<><select className="field" name="budget"><option value="">Estimated budget</option><option>Below GHS 5,000</option><option>GHS 5,000 – 15,000</option><option>GHS 15,000 – 40,000</option><option>Above GHS 40,000</option></select><input className="field" name="timeline" placeholder="Preferred timeline"/><textarea className="field min-h-28" name="requirements" placeholder="Describe the project and required features" required minLength={10}/></>:<><label className="label">Preferred date and time<input className="field" name="preferredDate" type="datetime-local" required/></label><textarea className="field min-h-24" name="notes" placeholder="What would you like to discuss?"/></>}{status&&<div className={`rounded-xl px-3 py-2 text-sm ${status.startsWith("Submitted")?"bg-emerald-50 text-emerald-700":"bg-red-50 text-red-700"}`}>{status}</div>}<button disabled={loading} className="btn-primary w-full">{loading?<Loader2 className="animate-spin" size={17}/>:kind==="quote"?<CheckCircle2 size={17}/>:<CalendarDays size={17}/>} {loading?"Submitting…":kind==="quote"?"Submit quote request":"Request consultation"}</button></form>}
